<?php

/* Generated by settings.php in /admin */

$get_software_update = "http://rwavechicago.com";     //Check for software updates

$mysql_host = "localhost";

$mysql_database = "";

$mysql_user = "";

$mysql_password = "";

//Facebook functions
$rpx_api_id = "";

$rpx_api_key = "";


$title = "Devel Server";
$slogan = "computers are people too";

$domain = "http://".$_SERVER['SERVER_NAME'];

$default_bgcolor = "#556B2F";     //default bgcolor when not logged in
$default_fontcolor = "#000000"; //default fontcolor when not logged in

$gv_email = "";         //email account attached to Google Voice
$gv_password = "";   //password for Google Voice
$gv_default_phone = ""; //default phone to recieve alerts 

?>