<?php
ob_start();
if(!$auth->isSuper()) { //is not super
	if(!$auth->isAdmin()) { //is not admin
		if(!$auth->isArtist()) { //is not artist
			if(!$auth->isUser()) { //is not logged in
				$pageTitle = "Please Login.";
				$page = "login"; //redirect login; not public
				//is public
				//do public stuff here
			}
			else $page = "block"; //redirect unauthorized; not admin
			//is user
			//do user stuff here
		}
		else $page = "block"; //redirect unauthorized; not super
		//is artist
		//do artist stuff here
		
	}
	else $page = "block"; //redirect unauthorized; not super
	 //is admin
	 //do admin stuff here

}
//is super
//do super stuff here

$pageTitle = "Website Settings";
$save = (isset($_POST['save']) ? true : false);
$revert = (isset($_POST['revert']) ? true : false);

if($save) {

$get_update_url = strip_tags($_POST['update_url']);

$get_title = strip_tags($_POST['title']);
$get_slogan = strip_tags($_POST['slogan']);


$get_appid = strip_tags($_POST['app_id']);
$get_secret = strip_tags($_POST['secret']);

$get_bgcolor = strip_tags($_POST['default_bg_color']);
$get_fontcolor = strip_tags($_POST['default_font_color']);

$get_host = strip_tags($_POST['mysql_server']);
$get_db = strip_tags($_POST['mysql_db']);
$get_user = strip_tags($_POST['mysql_user']);
$get_password = strip_tags($_POST['mysql_password']);

$get_gv_phone = strip_tags($_POST['default_phone']);
$get_gv_email = strip_tags($_POST['gv_email']);
$get_gv_password = strip_tags($_POST['gv_password']);
$settings = "<?php

/* Generated by settings.php in /admin */

\$get_software_update = \"$get_update_url\";     //Check for software updates

\$mysql_host = \"$get_host\";

\$mysql_database = \"$get_db\";

\$mysql_user = \"$get_user\";

\$mysql_password = \"$get_password\";

//Facebook functions
\$rpx_api_id = \"$get_appid\";

\$rpx_api_key = \"$get_secret\";


\$title = \"$get_title\";
\$slogan = \"$get_slogan\";

\$domain = \"http://\".\$_SERVER['SERVER_NAME'];

\$default_bgcolor = \"$get_bgcolor\";     //default bgcolor when not logged in
\$default_fontcolor = \"$get_fontcolor\"; //default fontcolor when not logged in

\$gv_email = \"$get_gv_email\";         //email account attached to Google Voice
\$gv_password = \"$get_gv_password\";   //password for Google Voice
\$gv_default_phone = \"$get_gv_phone\"; //default phone to recieve alerts 

?>";


	if(copy(SITE_PATH."/modules/settings.php", SITE_PATH."/modules/settings.bak.php") === FALSE) 
		exit("Could not backup settings.");

	if($file->write($settings,SITE_PATH."/modules/settings.php") === FALSE)
		 exit("Settings were not saved.");

 ob_flush();
	header("Location: settings");
}

else if($revert) {

	if(copy(SITE_PATH."/modules/settings.bak.php", SITE_PATH."/modules/settings.php") === FALSE) 
		exit("Could not revert settings.");

}

?>