//
// Copyright (C) 2011 Solid State Networks, Inc.  All rights reserved.
//
// This usage of this software is restricted to entities which have signed a license agreement
// with Solid State Networks, Inc.
//
// Licenses are valid for only one PRODUCT usage.  Please see the license agreement for further details.
//

var Language = {
    "UI_Yes": "Yes",
    "UI_No": "No",
    "UI_Done": "Done",
    "UI_Finish": "Finish",
    "UI_Retry": "Retry",
	"UI_Cancel" : "Cancel",
	"UI_Continue" : "Continue",    
    "UI_LaunchChrome": "Launch&nbsp;Google&nbsp;Chrome",
    "UI_FlashPlayerInstaller": "Adobe Flash Player Installer",
    "UI_ReaderInstaller": "Adobe Reader Installer",
    "PatchBundleName_launcher": "Launcher",
    "PatchBundleName_downloader": "Downloader",
    "PatchBundleState_Downloading": "Downloading",
    "PatchBundleState_Loading": "Initializing",
    "PatchBundleState_Complete": "Loaded",
    "PatchBundleState_Failed": "Failed to initialize",
    "ActionList_Download": "Retrieving install",
    "ActionList_Pending": "Pending",
    "ActionList_Error": "Failed",
    "ActionList_ErrorHeader": "Installation encountered errors",
    "ActionList_ErrorMessage": "Actionlist not found",
    "ActionList_AlreadyExists": "Note: Application is already installed",
    "ActionList_Complete": "Installation Complete", 
    "ActionList_AuthFailed": "Authorization Failed",
    "ActionList_RebootHeader": "Reboot required",
    "ActionList_RebootMessage": "One of the installations requires a reboot.  Do you wish to perform it now?",
    "ActionList_EarlyExitHeader": "Stop installing all applications?", //?
    "ActionList_StillRunning": "Installation still in progress. Once installation is complete, stop installing all other applications?",
    // "ActionList_StillDownloading": "Installation(s) currently downloading.  Do you wish to cancel and exit?",
    "ActionList_StillDownloading": "",    
    "ActionList_ConflictingProcessMessage": "Please close the following programs to continue.",
	"ActionList_ConflictingProcessReaderMessage" : "Adobe Reader is currently running.  Please close the Adobe Reader application and all web browsers and click &#8216;Retry&#8217;.",
	"ActionList_ConflictingProcessFlashPlayerSettingsMessage" : "The Flash Player Settings Manager is currently open.<br/><br/>Please close the Flash Player Settings Manager and try again.",
    "ActionList_ExtendedErrorLink": "Show error details",
    "ActionList_ExtendedError": "There was an error installing {Item}.",
    "ActionList_ExtendedErrorHeader": "{Item} installation error",
    "Launch_Start": "Installing",
    "Launch_Pend": "Installation Pending",
    "Launch_NotFound": "Error: General installation error",
    "Launch_Fail": "Failed to launch application",
    "DownloadState_Idle": "Download Idle",
    "DownloadState_Starting": "Download Starting",
    "DownloadState_Stopping": "Download Stopping",
    "DownloadState_Paused": "Download Paused",
    "DownloadState_Resuming": "Download Resuming",
    "DownloadState_Creating": "Creating Download",
    "DownloadState_Checking": "Checking Download",
    "DownloadState_Failure": "Download Failure",
    "DownloadState_Downloading": "Downloading",
    "DownloadState_Downloading/Checking": "Downloading/Checking",
    "DownloadState_Downloading/Stalled": "Download Timeout",
    "DownloadState_Complete": "Download Complete",
    "DownloadState_Seeding": "Download Seeding",
    "DownloadError_None": "No download error detected",
    "DownloadError_Unknown": "Unknown download error",
    "DownloadError_InvalidMetafile": "Unable to load metafile",
	"DownloadError_MetafileDownloadFailed": "Metafile download failed",
    "DownloadError_AlreadyDownloading": "Already downloading",
    "DownloadError_NotEnoughSpace": "Not enough disk space",
    "DownloadError_UnacceptableSource": "Unacceptable source found",
    "DownloadError_InvalidSource": "Invalid source found",
    "DownloadError_ConfigParseFailed": "Download configuration failed",
    "DownloadError_ConfigDownloadFailed": "Unable to retrieve download configuration",
    "DownloadError_ConfigUnzipFailed": "Download configuration failed",
    "DownloadError_DownloadFailed": "Download failed",
    "DownloadError_ReliableSourceContact": "Cannot contact reliable source",
    "DownloadError_ReliableSourceBadIntegrity": "Corrupt content from reliable source",
    "DownloadError_TrackerListEmpty": "Unable to find trackers",
    "DownloadError_TrackerContact": "Unable to contact trackers",
    "DownloadError_PeerListEmpty": "Cannot contact peers",
    "DownloadError_PeerNoGoodOnes": "Not connected to reliable peers",
    "AdobeFlashPlayer_ExitCode_1003": "Error: Unknown error",
    "AdobeFlashPlayer_ExitCode_1011": "Error: Update already in progress",
    "AdobeFlashPlayer_ExitCode_1012": "Error: Admin permissions required for installation",
    "AdobeFlashPlayer_ExitCode_1013": "Note: Newer version already installed",
    "AdobeFlashPlayer_ExitCode_1022": "Error: Admin permissions required for installation",
    "AdobeFlashPlayer_ExitCode_1025": "Error: Application currently in use",
    "AdobeFlashPlayer_ExitCode_1032": "Error: Failed to register",
    "AdobeFlashPlayer_ExitCode_1038": "Note: Application already installed",
    "AdobeFlashPlayer_ExitCode_1039": "Error: Installation failed",
    "AirRedistributionHelper_ExitCode_2": "Error: Usage error",
    "AirRedistributionHelper_ExitCode_3": "Error: Runtime not found",
    "AirRedistributionHelper_ExitCode_4": "Error: Loading runtime failed",
    "AirRedistributionHelper_ExitCode_5": "Error: Unknown error",
    "AirRedistributionHelper_ExitCode_6": "Error: Installation canceled",
    "AirRedistributionHelper_ExitCode_7": "Error: Installation failed",
    "AirRedistributionHelper_ExitCode_8": "Error: Update already in progress",
    "AirRedistributionHelper_ExitCode_9": "Note: Application already installed",
    "McAfeeSecurityScanner_ExitCode_1603": "Error: Installation failed",
    "McAfeeSecurityScanner_ExitCode_1": "Error: Installation failed",
    "McAfeeSecurityScanner_ExitCode_2": "Error: Installation failed",
    "GoogleToolbarCheck_ExitCode_1": "Note: Application already installed",
    "GoogleToolbarCheck_ExitCode_2": "Error: Admin permissions required for installation",
    "GoogleToolbarCheck_ExitCode_4": "Note: IE is not default browser",
    "GoogleToolbarCheck_ExitCode_8": "Note: Browser helper object disabled",
    "GoogleToolbarCheck_ExitCode_10": "Note: IE below minimum version",
    "GoogleToolbar_ExitCode_2147746307": "Error: Installation canceled",
    "GoogleToolbar_ExitCode_2147500037": "Error: Installation failed",
    "GoogleToolbar_ExitCode_2147746310": "Note: Application already installed",
    "GoogleToolbar_ExitCode_2147746308": "Error: Executable not run for safety reasons",
    "GoogleToolbar_ExitCode_2147746309": "Loaded:",
    "GoogleToolbar_ExitCode_2147746310": "Note: Newer version already installed",
    "GoogleToolbar_ExitCode_2147746311": "Error: Application currently in use",
    "GoogleToolbar_ExitCode_2147746313": "Error: Manifest download failed or manifest corrupted",
    "GoogleToolbar_ExitCode_2147746314": "Error: Manifest download failed or manifest corrupted",
    "GoogleToolbar_ExitCode_2147746315": "Error: A file was still in use",
    "GoogleToolbar_ExitCode_-2147220989": "Error: Installation canceled",
    "GoogleToolbar_ExitCode_-2147467259": "Error: Installation failed",
    "GoogleToolbar_ExitCode_-2147220986": "Note: Application already installed",
    "GoogleToolbar_ExitCode_-2147220988": "Error: Executable not run for safety reasons",
    "GoogleToolbar_ExitCode_-2147220987": "Error: No manifest available",
    "GoogleToolbar_ExitCode_-2147220986": "Note: Newer version already installed",
    "GoogleToolbar_ExitCode_-2147220985": "Error: Application currently in use",
    "GoogleToolbar_ExitCode_-2147220983": "Error: Manifest download failed or manifest corrupted",
    "GoogleToolbar_ExitCode_-2147220982": "Error: Manifest download failed or manifest corrupted",
    "GoogleToolbar_ExitCode_-2147220981": "Error: A file was still in use",
    "GoogleChromeCheck_ExitCode_1": "Chrome is already installed on the machine at the user level mode.",
    "GoogleChromeCheck_ExitCode_2": "Chrome is already installed on the machine at the system level mode.",
    "GoogleChromeCheck_ExitCode_4": "The user does not have sufficient privileges to install Chrome.",
    "GoogleChromeCheck_ExitCode_8": "The Operating System does not support Chrome.",
    "GoogleChromeCheck_ExitCode_32": "The current user is an Admin but is running in non-elevated mode.(applies to machines with Vista)",
    "ProxyDialog_Header" : "Authenticating Proxy Credentials",
	"ProxyDialog_Message" : "Please enter your proxy server credentials to continue.",
	"ProxyDialog_Server" : "Server",
	"ProxyDialog_Port" : "Port",
    "ProxyDialog_Realm" : "Realm",
	"ProxyDialog_UserName" : "Username",
	"ProxyDialog_Password" : "Password ",
	"ProxyDialog_ConnectionErrorHeader" : "Connection Error",
	"ProxyDialog_UnableToConnect" : "Unable to establish connection with proxy server. Username and password may not be correct."
};
